name: Build Faculty Handbook

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write   # allow workflow to push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.ACTIONS_PAT }}   # Your Personal Access Token

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Commit and push _site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _site
          git commit -m "Build site" || echo "No changes to commit"
          # Use PAT to push
          git remote set-url origin https://x-access-token:${PAT}@github.com/narasimhan-2604/fachandbook.git
          git push origin HEAD:main